### ISSUE TITLE
Import Graph Error

### ISSUE THREAD

**Issue by sashank06** [williamleif/socialsent#12]
Hi,
    When I try to run the example.py file I run into this error. 
    from keras.models import Graph
ImportError: cannot import name Graph
 I heard Keras removed Graph function. So is there any alternative to do this and make this work ?

**Comment by williamleif** [comment]
Hi,

Yes currently, there the code is only compatible with Keras 0.3 and not the newer versions. I am hoping to fix this, but I am quite busy with other projects at the moment. I've relabelled this issue as an enhancement to make the code work with Keras > 0.3.

If you have insight on what is necessary, or even feel motivated to make the changes, I would happily support that though (e.g., via a pull request).
